---
# unpack the packer distribution
- name: unpack packer
  tags: packerio
  unarchive:
    src={{ ansible_local_data_path }}/{{ packerio_filename }}
    dest={{ packerio_install_dir }}/{{ packerio_version }}
  notify: binlink packer

# provide symlinks in $PATH
- name: binlink packer
  tags: packerio
  file:
    state=link
    force=true
    src={{ item }}
    dest="{{ packerio_bin_path }}/{{ item | basename }}"
  with_fileglob: packerio_install_dir + '/' + packerio_version + '/packer*'
  when: packerio_bin_path != packerio_install_dir
